### ISSUE TITLE
Home Page - Landing Section

### ISSUE THREAD

**Issue by circlegov** [Code-4-Community/c4cneuv2#6]
![Image](https://github.com/user-attachments/assets/e9d27ee1-1251-4ede-adda-74a9e5c2f36a)

[Figma](https://www.figma.com/proto/5sJ9C5WRu3nRGW6hk2aEEt/C4C-Website-Redesign?page-id=1205%3A2136&node-id=1205-2968&node-type=canvas&viewport=808%2C266%2C0.06&t=vFVx0Qxjy82R3f4l-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=1205%3A2968&show-proto-sidebar=1)

Create a React component for the landing section shown in the screenshot. It should have a title, subtitle, and four images as shown in the Figma.

_For now, the styling is not important but the structure should match the screenshot above._

**Comment by GriffinMichalak** [comment]
### ℹ️ Issue

Closes Landing Page

### 📝 Description

Added MissionStatement component in landing.tsx to add contents to be seen on landing page.

### ✔️ Verification
<img width="1492" alt="image" src="https://github.com/user-attachments/assets/983ac442-6f7b-49cc-b35e-0df6ebf99604">

### 🏕️ (Optional) Future Work / Notes
(Code still runs)
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/af260bba-166b-4cd6-aa15-aba60ddeaef6">
